export default {
  name: 'product',
  title: 'Product',
  type: 'document',
  fields: [
    { name:'name',    title:'Product Name',  type:'string',  validation: R => R.required() },
    { name:'brand',   title:'Brand',         type:'string'  },
    { name:'price',   title:'Price (INR)',   type:'number',  validation: R => R.required() },
    { name:'originalPrice', title:'Original Price', type:'number' },
    { name:'category', title:'Category',    type:'string',
      options:{ list:['tv','fridge','washing','ac','audio','camera','kitchen'] }},
    { name:'description', title:'Short Description', type:'text', rows: 3 },
    { name:'longDescription', title:'Full Description', type:'text', rows: 6 },
    { name:'image',   title:'Main Image',   type:'image', options:{hotspot:true} },
    { name:'gallery', title:'Extra Images', type:'array', of:[{type:'image'}] },
    { name:'stock',   title:'Stock Quantity', type:'number' },
    { name:'featured',  title:'Featured Product?', type:'boolean' },
    { name:'trending',  title:'Trending?',         type:'boolean' },
    { name:'badge',   title:'Badge Text (e.g. BESTSELLER)', type:'string' },
    { name:'badgeType', title:'Badge Color',  type:'string',
      options:{list:['gold','red','blue','green']} },
    { name:'rating',  title:'Rating (out of 5)', type:'number' },
    { name:'reviews', title:'Number of Reviews',  type:'number' },
    // { name:'emi',     title:'EMI Text (e.g. 2,999/mo)', type:'string' },
    { name:'delivery', title:'Delivery Time',    type:'string' },
    { name:'whatsapp', title:'WhatsApp Number (91XXXXXXXXXX)', type:'string' },
    { name:'installation', title:'Free Installation?', type:'boolean' },
  ]
}
